// ---------------------------------------------------------------------------
// Seed script: generates all entry files from baked-in data
// ---------------------------------------------------------------------------

import { writeFileSync, mkdirSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import YAML from 'yaml';

const ROOT = join(fileURLToPath(import.meta.url), '..', '..');

function ensureDir(dir) {
  mkdirSync(dir, { recursive: true });
}

function writeMcpServer(entry) {
  const dir = join(ROOT, 'mcp-servers');
  ensureDir(dir);
  const content = YAML.stringify(entry, { lineWidth: 120 });
  writeFileSync(join(dir, `${entry.slug}.yaml`), content);
}

function writeContentEntry(entry) {
  const { markdownBody, contentType, ...frontmatterData } = entry;
  const dirMap = { agent: 'agents', skill: 'skills', workflow: 'workflows', rule: 'rules', template: 'templates', knowledge: 'knowledge', spec: 'spec' };
  const subdir = dirMap[contentType] || contentType;
  const dir = join(ROOT, 'content', subdir);
  ensureDir(dir);
  const fm = YAML.stringify({ ...frontmatterData, contentType }, { lineWidth: 120 });
  const content = `---\n${fm}---\n\n${markdownBody}\n`;
  writeFileSync(join(dir, `${frontmatterData.slug}.md`), content);
}

// ── MCP Servers (18) ─────────────────────────────────────────────

const mcpServers = [
  { slug: 'filesystem', name: 'Filesystem', description: 'Read, write, and manage files and directories securely', author: 'Anthropic', authorUrl: 'https://github.com/anthropics', githubUrl: 'https://github.com/modelcontextprotocol/servers/tree/main/src/filesystem', category: 'file-system', tags: ['filesystem', 'files', 'directories', 'official'], transport: ['stdio'], features: ['Read files', 'Write files', 'List directories', 'Search files', 'Move/copy files'], compatibility: ['claude-code', 'cursor', 'vscode', 'windsurf'], configSnippet: { mcpServers: { filesystem: { command: 'npx', args: ['-y', '@modelcontextprotocol/server-filesystem', '/path/to/allowed'] } } }, createdAt: '2024-11-25', updatedAt: '2026-01-15' },
  { slug: 'github', name: 'GitHub', description: 'Interact with GitHub repositories, issues, pull requests, and more', author: 'GitHub', authorUrl: 'https://github.com/github', githubUrl: 'https://github.com/modelcontextprotocol/servers/tree/main/src/github', category: 'devtools', tags: ['github', 'git', 'repositories', 'issues', 'pull-requests', 'official'], transport: ['stdio'], features: ['Repository management', 'Issue tracking', 'Pull request operations', 'Code search', 'Branch management'], compatibility: ['claude-code', 'cursor', 'vscode', 'windsurf'], configSnippet: { mcpServers: { github: { command: 'npx', args: ['-y', '@modelcontextprotocol/server-github'], env: { GITHUB_PERSONAL_ACCESS_TOKEN: '<your-token>' } } } }, createdAt: '2024-11-25', updatedAt: '2026-01-20' },
  { slug: 'brave-search', name: 'Brave Search', description: 'Web and local search using the Brave Search API', author: 'Anthropic', githubUrl: 'https://github.com/modelcontextprotocol/servers/tree/main/src/brave-search', category: 'search', tags: ['search', 'web', 'brave', 'official'], transport: ['stdio'], features: ['Web search', 'Local search', 'News search', 'Image search'], compatibility: ['claude-code', 'cursor', 'vscode'], configSnippet: { mcpServers: { 'brave-search': { command: 'npx', args: ['-y', '@modelcontextprotocol/server-brave-search'], env: { BRAVE_API_KEY: '<your-key>' } } } }, createdAt: '2024-11-25', updatedAt: '2026-01-10' },
  { slug: 'puppeteer', name: 'Puppeteer', description: 'Browser automation for web scraping, screenshots, and testing', author: 'Anthropic', githubUrl: 'https://github.com/modelcontextprotocol/servers/tree/main/src/puppeteer', category: 'browser', tags: ['browser', 'automation', 'scraping', 'screenshots', 'official'], transport: ['stdio'], features: ['Navigate pages', 'Take screenshots', 'Click elements', 'Fill forms', 'Execute JavaScript'], compatibility: ['claude-code', 'cursor', 'vscode'], configSnippet: { mcpServers: { puppeteer: { command: 'npx', args: ['-y', '@modelcontextprotocol/server-puppeteer'] } } }, createdAt: '2024-11-25', updatedAt: '2026-01-18' },
  { slug: 'postgres', name: 'PostgreSQL', description: 'Read-only access to PostgreSQL databases with schema inspection', author: 'Anthropic', githubUrl: 'https://github.com/modelcontextprotocol/servers/tree/main/src/postgres', category: 'database', tags: ['database', 'postgresql', 'sql', 'official'], transport: ['stdio'], features: ['Query execution', 'Schema inspection', 'Table listing', 'Index info'], compatibility: ['claude-code', 'cursor', 'vscode'], configSnippet: { mcpServers: { postgres: { command: 'npx', args: ['-y', '@modelcontextprotocol/server-postgres', 'postgresql://localhost/mydb'] } } }, createdAt: '2024-11-25', updatedAt: '2026-01-12' },
  { slug: 'sqlite', name: 'SQLite', description: 'Read and write SQLite databases with full SQL support', author: 'Anthropic', githubUrl: 'https://github.com/modelcontextprotocol/servers/tree/main/src/sqlite', category: 'database', tags: ['database', 'sqlite', 'sql', 'official'], transport: ['stdio'], features: ['Query execution', 'Table management', 'Schema inspection', 'Data export'], compatibility: ['claude-code', 'cursor', 'vscode'], configSnippet: { mcpServers: { sqlite: { command: 'uvx', args: ['mcp-server-sqlite', '--db-path', '/path/to/db.sqlite'] } } }, createdAt: '2024-11-25', updatedAt: '2026-01-12' },
  { slug: 'slack', name: 'Slack', description: 'Read and send messages, manage channels in Slack workspaces', author: 'Anthropic', githubUrl: 'https://github.com/modelcontextprotocol/servers/tree/main/src/slack', category: 'communication', tags: ['slack', 'messaging', 'channels', 'official'], transport: ['stdio'], features: ['Send messages', 'Read channels', 'List users', 'Search messages'], compatibility: ['claude-code', 'cursor', 'vscode'], configSnippet: { mcpServers: { slack: { command: 'npx', args: ['-y', '@modelcontextprotocol/server-slack'], env: { SLACK_BOT_TOKEN: '<your-token>' } } } }, createdAt: '2024-12-01', updatedAt: '2026-01-10' },
  { slug: 'sequential-thinking', name: 'Sequential Thinking', description: 'Dynamic, reflective problem-solving through structured thought sequences', author: 'Anthropic', githubUrl: 'https://github.com/modelcontextprotocol/servers/tree/main/src/sequentialthinking', category: 'ai-llm', tags: ['reasoning', 'thinking', 'problem-solving', 'official'], transport: ['stdio'], features: ['Structured reasoning', 'Thought revision', 'Branch exploration', 'Hypothesis adjustment'], compatibility: ['claude-code', 'cursor', 'vscode'], configSnippet: { mcpServers: { 'sequential-thinking': { command: 'npx', args: ['-y', '@modelcontextprotocol/server-sequential-thinking'] } } }, createdAt: '2025-01-15', updatedAt: '2026-01-20' },
  { slug: 'context7', name: 'Context7', description: 'Up-to-date documentation and code examples for any library', author: 'Upstash', authorUrl: 'https://github.com/upstash', githubUrl: 'https://github.com/upstash/context7', category: 'devtools', tags: ['documentation', 'docs', 'libraries', 'code-examples'], transport: ['stdio'], features: ['Library documentation lookup', 'Code examples', 'Version-aware docs', 'API reference'], compatibility: ['claude-code', 'cursor', 'vscode', 'windsurf'], configSnippet: { mcpServers: { context7: { command: 'npx', args: ['-y', '@upstash/context7-mcp@latest'] } } }, createdAt: '2025-04-01', updatedAt: '2026-01-25' },
  { slug: 'playwright', name: 'Playwright', description: 'Browser automation using Playwright for testing and scraping', author: 'Microsoft', authorUrl: 'https://github.com/microsoft', githubUrl: 'https://github.com/microsoft/playwright-mcp', category: 'browser', tags: ['browser', 'automation', 'testing', 'playwright'], transport: ['stdio'], features: ['Navigate pages', 'Take screenshots', 'Form interaction', 'Multi-browser support', 'Network interception'], compatibility: ['claude-code', 'cursor', 'vscode'], configSnippet: { mcpServers: { playwright: { command: 'npx', args: ['-y', '@playwright/mcp@latest'] } } }, createdAt: '2025-03-10', updatedAt: '2026-01-22' },
  { slug: 'sentry', name: 'Sentry', description: 'Error tracking and performance monitoring integration', author: 'Sentry', authorUrl: 'https://github.com/getsentry', githubUrl: 'https://github.com/getsentry/sentry-mcp', category: 'monitoring', tags: ['errors', 'monitoring', 'performance', 'debugging'], transport: ['stdio'], features: ['Error retrieval', 'Issue search', 'Performance data', 'Stack trace analysis'], compatibility: ['claude-code', 'cursor', 'vscode'], configSnippet: { mcpServers: { sentry: { command: 'npx', args: ['-y', '@sentry/mcp-server@latest'], env: { SENTRY_AUTH_TOKEN: '<your-token>' } } } }, createdAt: '2025-02-15', updatedAt: '2026-01-18' },
  { slug: 'supabase', name: 'Supabase', description: 'Manage Supabase projects, databases, and edge functions', author: 'Supabase', authorUrl: 'https://github.com/supabase', githubUrl: 'https://github.com/supabase-community/supabase-mcp', category: 'database', tags: ['supabase', 'database', 'auth', 'storage', 'edge-functions'], transport: ['stdio'], features: ['Database queries', 'Schema management', 'Auth operations', 'Storage management', 'Edge function deployment'], compatibility: ['claude-code', 'cursor', 'vscode'], configSnippet: { mcpServers: { supabase: { command: 'npx', args: ['-y', 'supabase-mcp-server@latest'], env: { SUPABASE_URL: '<url>', SUPABASE_SERVICE_ROLE_KEY: '<key>' } } } }, createdAt: '2025-02-20', updatedAt: '2026-01-28' },
  { slug: 'cloudflare', name: 'Cloudflare', description: 'Manage Cloudflare Workers, KV, R2, and D1 resources', author: 'Cloudflare', authorUrl: 'https://github.com/cloudflare', githubUrl: 'https://github.com/cloudflare/mcp-server-cloudflare', category: 'cloud', tags: ['cloudflare', 'workers', 'kv', 'r2', 'd1', 'edge'], transport: ['stdio'], features: ['Workers management', 'KV store operations', 'R2 storage', 'D1 database', 'DNS management'], compatibility: ['claude-code', 'cursor', 'vscode'], configSnippet: { mcpServers: { cloudflare: { command: 'npx', args: ['-y', '@cloudflare/mcp-server-cloudflare'], env: { CLOUDFLARE_API_TOKEN: '<your-token>' } } } }, createdAt: '2025-01-20', updatedAt: '2026-01-15' },
  { slug: 'linear', name: 'Linear', description: 'Issue tracking and project management with Linear', author: 'Linear', authorUrl: 'https://github.com/linear', githubUrl: 'https://github.com/linear/linear-mcp-server', category: 'devtools', tags: ['linear', 'issues', 'project-management', 'agile'], transport: ['stdio'], features: ['Create issues', 'Search issues', 'Update status', 'List projects', 'Team management'], compatibility: ['claude-code', 'cursor', 'vscode'], configSnippet: { mcpServers: { linear: { command: 'npx', args: ['-y', '@linear/mcp-server'], env: { LINEAR_API_KEY: '<your-key>' } } } }, createdAt: '2025-03-05', updatedAt: '2026-01-20' },
  { slug: 'exa-search', name: 'Exa Search', description: 'AI-powered web search with content extraction', author: 'Exa', authorUrl: 'https://github.com/exa-labs', githubUrl: 'https://github.com/exa-labs/exa-mcp-server', category: 'search', tags: ['search', 'web', 'ai', 'content-extraction'], transport: ['stdio'], features: ['Semantic search', 'Content extraction', 'Similar page finding', 'Keyword search'], compatibility: ['claude-code', 'cursor', 'vscode'], configSnippet: { mcpServers: { exa: { command: 'npx', args: ['-y', 'exa-mcp-server'], env: { EXA_API_KEY: '<your-key>' } } } }, createdAt: '2025-01-10', updatedAt: '2026-01-15' },
  { slug: 'tavily', name: 'Tavily Search', description: 'AI-optimized search API designed for LLM applications', author: 'Tavily', authorUrl: 'https://github.com/tavily-ai', githubUrl: 'https://github.com/tavily-ai/tavily-mcp', category: 'search', tags: ['search', 'web', 'ai', 'research'], transport: ['stdio'], features: ['Web search', 'Content extraction', 'Research mode', 'Domain filtering'], compatibility: ['claude-code', 'cursor', 'vscode'], configSnippet: { mcpServers: { tavily: { command: 'npx', args: ['-y', 'tavily-mcp@latest'], env: { TAVILY_API_KEY: '<your-key>' } } } }, createdAt: '2025-02-01', updatedAt: '2026-01-18' },
  { slug: 'neon', name: 'Neon', description: 'Serverless Postgres management with branching and autoscaling', author: 'Neon', authorUrl: 'https://github.com/neondatabase', githubUrl: 'https://github.com/neondatabase/mcp-server-neon', category: 'database', tags: ['neon', 'postgres', 'serverless', 'database', 'branching'], transport: ['stdio'], features: ['Database branching', 'Query execution', 'Schema management', 'Autoscaling control'], compatibility: ['claude-code', 'cursor', 'vscode'], configSnippet: { mcpServers: { neon: { command: 'npx', args: ['-y', '@neondatabase/mcp-server-neon'], env: { NEON_API_KEY: '<your-key>' } } } }, createdAt: '2025-03-01', updatedAt: '2026-01-20' },
  { slug: 'vercel', name: 'Vercel', description: 'Manage Vercel deployments, projects, and environment variables', author: 'Vercel', authorUrl: 'https://github.com/vercel', githubUrl: 'https://github.com/vercel/mcp-server-vercel', category: 'cloud', tags: ['vercel', 'deployment', 'hosting', 'edge'], transport: ['stdio'], features: ['Deploy management', 'Project config', 'Environment variables', 'Domain management', 'Log streaming'], compatibility: ['claude-code', 'cursor', 'vscode'], configSnippet: { mcpServers: { vercel: { command: 'npx', args: ['-y', '@vercel/mcp-server-vercel'], env: { VERCEL_TOKEN: '<your-token>' } } } }, createdAt: '2025-02-10', updatedAt: '2026-01-22' },
];

// ── Content helper ───────────────────────────────────────────────

const GH = 'https://github.com/DerianAndre/aidd.md';
function c(slug, name, desc, ct, tags, compat, cmd, body, o = {}) {
  return { slug, name, description: desc, contentType: ct, author: o.author || 'aidd.md', ...(o.authorUrl && { authorUrl: o.authorUrl }), ...(o.githubUrl && { githubUrl: o.githubUrl }), tags, compatibility: compat, ...(cmd && { installCommand: cmd }), createdAt: o.createdAt || '2025-06-01', updatedAt: o.updatedAt || '2026-02-01', markdownBody: body };
}

const contentEntries = [
  // Agents (9)
  c('master-orchestrator', 'Master Orchestrator', 'Strategic mapping & delegation — decomposes user intent, queries TKB, maps execution paths', 'agent', ['orchestration', 'delegation', 'routing', 'strategy', 'core'], ['claude-code', 'cursor'], 'npx @aidd.md/cli install agent master-orchestrator', '# Master Orchestrator\n\nStrategic mapping and delegation. Decomposes user intent, queries Technology Knowledge Base, and maps optimal execution paths.', { githubUrl: `${GH}/blob/main/AGENTS.md` }),
  c('knowledge-architect-agent', 'Knowledge Architect', 'TKB curator & schema enforcer — maintains Technology Knowledge Base, validates schema compliance', 'agent', ['knowledge-base', 'schema', 'curation', 'validation'], ['claude-code', 'cursor'], 'npx @aidd.md/cli install agent knowledge-architect', '# Knowledge Architect Agent\n\nMaintains the Technology Knowledge Base, validates schema compliance, and updates benchmarks.', { githubUrl: `${GH}/blob/main/AGENTS.md` }),
  c('system-architect-agent', 'System Architect', 'Complete system design — architecture analysis, technical debt assessment, ADRs', 'agent', ['architecture', 'system-design', 'adr', 'technical-debt'], ['claude-code', 'cursor'], 'npx @aidd.md/cli install agent system-architect', '# System Architect Agent\n\nComplete system design, architecture analysis, and technical debt assessment.', { githubUrl: `${GH}/blob/main/AGENTS.md` }),
  c('fullstack-agent', 'Fullstack Agent', 'End-to-end implementation — complete features, integrations, full-stack development', 'agent', ['fullstack', 'implementation', 'integration', 'features'], ['claude-code', 'cursor'], 'npx @aidd.md/cli install agent fullstack', '# Fullstack Agent\n\nEnd-to-end implementation for complete features, integrations, and full-stack development.', { githubUrl: `${GH}/blob/main/AGENTS.md` }),
  c('interface-artisan-agent', 'Interface Artisan', 'UI/UX components — WCAG accessibility, pixel-perfect implementation, design systems', 'agent', ['ui', 'ux', 'accessibility', 'wcag', 'components'], ['claude-code', 'cursor'], 'npx @aidd.md/cli install agent interface-artisan', '# Interface Artisan Agent\n\nUI/UX component development with WCAG accessibility and pixel-perfect implementation.', { githubUrl: `${GH}/blob/main/AGENTS.md` }),
  c('quality-engineer-agent', 'Quality Engineer', 'Test generation — coverage analysis, edge cases, TDD workflows', 'agent', ['testing', 'tdd', 'coverage', 'quality', 'edge-cases'], ['claude-code', 'cursor'], 'npx @aidd.md/cli install agent quality-engineer', '# Quality Engineer Agent\n\nTest generation, coverage analysis, edge case discovery, and TDD workflows.', { githubUrl: `${GH}/blob/main/AGENTS.md` }),
  c('security-architect-agent', 'Security Architect', 'Security audits — vulnerability analysis, IAM, threat modeling, OWASP compliance', 'agent', ['security', 'audit', 'owasp', 'iam', 'threat-modeling'], ['claude-code', 'cursor'], 'npx @aidd.md/cli install agent security-architect', '# Security Architect Agent\n\nSecurity audits, vulnerability analysis, IAM patterns, and threat modeling.', { githubUrl: `${GH}/blob/main/AGENTS.md` }),
  c('platform-engineer-agent', 'Platform Engineer', 'CI/CD, infrastructure, deployment pipelines, monitoring, containerization', 'agent', ['cicd', 'infrastructure', 'deployment', 'monitoring', 'devops'], ['claude-code', 'cursor'], 'npx @aidd.md/cli install agent platform-engineer', '# Platform Engineer Agent\n\nCI/CD pipelines, infrastructure management, deployment, and monitoring.', { githubUrl: `${GH}/blob/main/AGENTS.md` }),
  c('i18n-specialist-agent', 'i18n Specialist', 'Internationalization — translation workflows, locale management, RTL support', 'agent', ['i18n', 'localization', 'translations', 'rtl', 'next-intl'], ['claude-code', 'cursor'], 'npx @aidd.md/cli install agent i18n-specialist', '# i18n Specialist Agent\n\nInternationalization patterns, translation workflows, and locale management.', { githubUrl: `${GH}/blob/main/AGENTS.md` }),
  // Skills (11)
  c('system-architect', 'System Architect', 'Design scalable system architectures — microservices, monoliths, event-driven patterns', 'skill', ['architecture', 'system-design', 'microservices', 'scalability', 'core'], ['claude-code', 'cursor'], 'npx @aidd.md/cli install skill system-architect', '# System Architect\n\nDesign scalable system architectures with trade-off analysis, ADRs, and infrastructure planning.', { authorUrl: GH, githubUrl: `${GH}/tree/main/skills/system-architect` }),
  c('contract-architect', 'Contract Architect', 'Design APIs, contracts, and integration boundaries — REST, GraphQL, gRPC, tRPC', 'skill', ['api', 'contracts', 'rest', 'graphql', 'grpc', 'trpc'], ['claude-code', 'cursor'], 'npx @aidd.md/cli install skill contract-architect', '# Contract Architect\n\nDesign type-safe API contracts, schema validation, and integration boundaries.', { githubUrl: `${GH}/tree/main/skills/contract-architect`, createdAt: '2025-06-15', updatedAt: '2026-01-28' }),
  c('interface-artisan', 'Interface Artisan', 'Craft pixel-perfect UI components — React, accessibility, design systems', 'skill', ['frontend', 'ui', 'components', 'react', 'accessibility'], ['claude-code', 'cursor'], 'npx @aidd.md/cli install skill interface-artisan', '# Interface Artisan\n\nBuild accessible, reusable UI components with design system consistency.', { githubUrl: `${GH}/tree/main/skills/interface-artisan`, createdAt: '2025-06-15', updatedAt: '2026-01-28' }),
  c('design-architect', 'Design Architect', 'UX/UI design intelligence — layouts, color systems, typography, motion design', 'skill', ['design', 'ux', 'ui', 'typography', 'color-systems', 'motion'], ['claude-code', 'cursor'], 'npx @aidd.md/cli install skill design-architect', '# Design Architect\n\nDesign systems, color palettes, typography scales, layout composition, and motion design.', { githubUrl: `${GH}/tree/main/skills/design-architect`, createdAt: '2025-07-01', updatedAt: '2026-01-25' }),
  c('experience-engineer', 'Experience Engineer', 'Performance optimization — Core Web Vitals, bundle size, rendering, caching', 'skill', ['performance', 'optimization', 'web-vitals', 'caching', 'rendering'], ['claude-code', 'cursor'], 'npx @aidd.md/cli install skill experience-engineer', '# Experience Engineer\n\nOptimize frontend performance — Core Web Vitals, bundle splitting, lazy loading, caching strategies.', { githubUrl: `${GH}/tree/main/skills/experience-engineer`, createdAt: '2025-07-01', updatedAt: '2026-01-20' }),
  c('data-architect', 'Data Architect', 'Database design — schemas, migrations, indexing, query optimization, ORMs', 'skill', ['database', 'schema', 'migrations', 'orm', 'sql', 'indexing'], ['claude-code', 'cursor'], 'npx @aidd.md/cli install skill data-architect', '# Data Architect\n\nDesign database schemas, write migrations, optimize queries, and configure ORMs.', { githubUrl: `${GH}/tree/main/skills/data-architect`, createdAt: '2025-07-15', updatedAt: '2026-01-22' }),
  c('quality-engineer', 'Quality Engineer', 'Testing strategies — unit, integration, e2e, mocking, coverage, TDD', 'skill', ['testing', 'tdd', 'unit-tests', 'e2e', 'coverage', 'mocking'], ['claude-code', 'cursor'], 'npx @aidd.md/cli install skill quality-engineer', '# Quality Engineer\n\nTest strategies, TDD workflows, mocking patterns, and coverage optimization.', { githubUrl: `${GH}/tree/main/skills/quality-engineer`, createdAt: '2025-08-01', updatedAt: '2026-01-18' }),
  c('security-architect', 'Security Architect', 'Security auditing — OWASP, threat modeling, auth patterns, vulnerability scanning', 'skill', ['security', 'owasp', 'auth', 'threat-modeling', 'vulnerabilities'], ['claude-code', 'cursor'], 'npx @aidd.md/cli install skill security-architect', '# Security Architect\n\nThreat modeling, OWASP compliance, auth patterns, and vulnerability analysis.', { githubUrl: `${GH}/tree/main/skills/security-architect`, createdAt: '2025-08-01', updatedAt: '2026-01-20' }),
  c('platform-engineer', 'Platform Engineer', 'CI/CD, infrastructure, Docker, Kubernetes, deployment pipelines', 'skill', ['cicd', 'docker', 'kubernetes', 'infrastructure', 'devops'], ['claude-code', 'cursor'], 'npx @aidd.md/cli install skill platform-engineer', '# Platform Engineer\n\nCI/CD pipelines, containerization, orchestration, and infrastructure as code.', { githubUrl: `${GH}/tree/main/skills/platform-engineer`, createdAt: '2025-08-15', updatedAt: '2026-01-18' }),
  c('knowledge-architect', 'Knowledge Architect', 'Documentation, knowledge bases, ADRs, technical writing', 'skill', ['documentation', 'knowledge-base', 'adr', 'technical-writing'], ['claude-code', 'cursor'], 'npx @aidd.md/cli install skill knowledge-architect', '# Knowledge Architect\n\nStructured documentation, ADRs, knowledge base management, and technical writing.', { githubUrl: `${GH}/tree/main/skills/knowledge-architect`, createdAt: '2025-09-01', updatedAt: '2026-01-15' }),
  c('i18n-specialist', 'i18n Specialist', 'Internationalization — translation workflows, locale management, RTL support', 'skill', ['i18n', 'localization', 'translations', 'rtl', 'locale'], ['claude-code', 'cursor'], 'npx @aidd.md/cli install skill i18n-specialist', '# i18n Specialist\n\nInternationalization workflows, translation management, locale configuration, and RTL support.', { githubUrl: `${GH}/tree/main/skills/i18n-specialist`, createdAt: '2025-09-01', updatedAt: '2026-01-12' }),
  // Workflows (9)
  c('analyze-workflow', 'Analyze Workflow', 'Deep codebase analysis — trace execution paths, map architecture, understand patterns', 'workflow', ['analysis', 'codebase', 'architecture', 'exploration'], ['claude-code'], 'npx @aidd.md/cli install workflow analyze', '# Analyze Workflow\n\nSystematic codebase exploration and architecture mapping.', { githubUrl: `${GH}/tree/main/workflows/analyze.md`, updatedAt: '2026-01-10' }),
  c('review-workflow', 'Review Workflow', 'Code review with confidence-based filtering and actionable feedback', 'workflow', ['code-review', 'quality', 'feedback', 'pr-review'], ['claude-code'], 'npx @aidd.md/cli install workflow review', '# Review Workflow\n\nStructured code review with evidence-based feedback.', { githubUrl: `${GH}/tree/main/workflows/review.md`, updatedAt: '2026-01-12' }),
  c('design-workflow', 'Design Workflow', 'End-to-end design process — research, wireframes, prototyping, handoff', 'workflow', ['design', 'wireframes', 'prototyping', 'ux-research'], ['claude-code'], 'npx @aidd.md/cli install workflow design', '# Design Workflow\n\nStructured design process from research through prototyping to developer handoff.', { githubUrl: `${GH}/tree/main/workflows/design.md`, createdAt: '2025-06-15', updatedAt: '2026-01-15' }),
  c('audit-workflow', 'Audit Workflow', 'Security and quality auditing — vulnerability scanning, compliance checks', 'workflow', ['audit', 'security', 'compliance', 'vulnerability-scanning'], ['claude-code'], 'npx @aidd.md/cli install workflow audit', '# Audit Workflow\n\nSystematic security and quality auditing with actionable remediation steps.', { githubUrl: `${GH}/tree/main/workflows/audit.md`, createdAt: '2025-07-01', updatedAt: '2026-01-18' }),
  c('test-workflow', 'Test Workflow', 'Testing pipeline — strategy selection, test writing, coverage analysis, CI integration', 'workflow', ['testing', 'coverage', 'ci', 'test-strategy'], ['claude-code'], 'npx @aidd.md/cli install workflow test', '# Test Workflow\n\nEnd-to-end testing pipeline from strategy through execution to coverage reporting.', { githubUrl: `${GH}/tree/main/workflows/test.md`, createdAt: '2025-07-01', updatedAt: '2026-01-15' }),
  c('feature-branch-workflow', 'Feature Branch Workflow', 'Git branching strategy — feature branches, PR workflow, merge strategies', 'workflow', ['git', 'branching', 'pull-requests', 'merge-strategy'], ['claude-code'], 'npx @aidd.md/cli install workflow feature-branch', '# Feature Branch Workflow\n\nGit branching strategies, PR workflows, and merge conflict resolution.', { githubUrl: `${GH}/tree/main/workflows/feature-branch.md`, createdAt: '2025-07-15', updatedAt: '2026-01-20' }),
  c('docs-workflow', 'Documentation Workflow', 'Documentation generation — API docs, guides, changelogs, README templates', 'workflow', ['documentation', 'api-docs', 'changelog', 'readme'], ['claude-code'], 'npx @aidd.md/cli install workflow docs', '# Documentation Workflow\n\nGenerate and maintain API docs, guides, changelogs, and README files.', { githubUrl: `${GH}/tree/main/workflows/docs.md`, createdAt: '2025-08-01', updatedAt: '2026-01-10' }),
  c('product-workflow', 'Product Workflow', 'Product development — user stories, acceptance criteria, sprint planning', 'workflow', ['product', 'user-stories', 'acceptance-criteria', 'sprint-planning'], ['claude-code'], 'npx @aidd.md/cli install workflow product', '# Product Workflow\n\nProduct development lifecycle from user stories to sprint planning.', { githubUrl: `${GH}/tree/main/workflows/product.md`, createdAt: '2025-08-15', updatedAt: '2026-01-12' }),
  c('technology-selection-workflow', 'Technology Selection Workflow', 'Structured technology evaluation — comparison matrices, proof of concepts, decision records', 'workflow', ['technology', 'evaluation', 'comparison', 'adr', 'decision-making'], ['claude-code'], 'npx @aidd.md/cli install workflow technology-selection', '# Technology Selection Workflow\n\nStructured evaluation framework for choosing technologies with ADRs.', { githubUrl: `${GH}/tree/main/workflows/technology-selection.md`, createdAt: '2025-09-01', updatedAt: '2026-01-15' }),
  // Rules (11)
  c('global-rules', 'Global Rules', 'Framework-wide immutable constraints — code style, naming, security, testing', 'rule', ['rules', 'conventions', 'code-style', 'global'], ['claude-code', 'cursor'], 'npx @aidd.md/cli install rule global', '# Global Rules\n\nImmutable framework constraints applied to all agents and tasks.', { githubUrl: `${GH}/tree/main/rules/global.md` }),
  c('orchestrator-rules', 'Orchestrator Rules', 'Orchestration constraints — agent selection, task routing, coordination protocols', 'rule', ['rules', 'orchestration', 'routing', 'coordination'], ['claude-code', 'cursor'], 'npx @aidd.md/cli install rule orchestrator', '# Orchestrator Rules\n\nConstraints for agent selection, task classification, and multi-agent coordination.', { githubUrl: `${GH}/tree/main/rules/orchestrator.md`, updatedAt: '2026-01-28' }),
  c('frontend-rules', 'Frontend Rules', 'Frontend constraints — React patterns, CSS conventions, accessibility requirements', 'rule', ['rules', 'frontend', 'react', 'css', 'accessibility'], ['claude-code', 'cursor'], 'npx @aidd.md/cli install rule frontend', '# Frontend Rules\n\nReact patterns, CSS conventions, component architecture, and accessibility requirements.', { githubUrl: `${GH}/tree/main/rules/frontend.md`, createdAt: '2025-07-01', updatedAt: '2026-01-28' }),
  c('backend-rules', 'Backend Rules', 'Backend constraints — API design, error handling, validation, database access patterns', 'rule', ['rules', 'backend', 'api', 'error-handling', 'validation'], ['claude-code', 'cursor'], 'npx @aidd.md/cli install rule backend', '# Backend Rules\n\nAPI design patterns, error handling, validation, and database access conventions.', { githubUrl: `${GH}/tree/main/rules/backend.md`, createdAt: '2025-07-01', updatedAt: '2026-01-25' }),
  c('security-rules', 'Security Rules', 'Security constraints — input validation, auth patterns, OWASP compliance', 'rule', ['rules', 'security', 'owasp', 'auth', 'input-validation'], ['claude-code', 'cursor'], 'npx @aidd.md/cli install rule security', '# Security Rules\n\nSecurity-first constraints covering OWASP, authentication, and input validation.', { githubUrl: `${GH}/tree/main/rules/security.md`, createdAt: '2025-07-15', updatedAt: '2026-01-22' }),
  c('testing-rules', 'Testing Rules', 'Testing constraints — coverage thresholds, naming conventions, test organization', 'rule', ['rules', 'testing', 'coverage', 'naming', 'organization'], ['claude-code', 'cursor'], 'npx @aidd.md/cli install rule testing', '# Testing Rules\n\nTest coverage thresholds, naming conventions, and test file organization.', { githubUrl: `${GH}/tree/main/rules/testing.md`, createdAt: '2025-08-01', updatedAt: '2026-01-18' }),
  c('interfaces-rules', 'Interfaces Rules', 'UI/UX constraints — responsive design, color systems, typography, spacing', 'rule', ['rules', 'ui', 'ux', 'responsive', 'design-system'], ['claude-code', 'cursor'], 'npx @aidd.md/cli install rule interfaces', '# Interfaces Rules\n\nUI/UX design constraints for responsive layouts, color systems, and typography.', { githubUrl: `${GH}/tree/main/rules/interfaces.md`, createdAt: '2025-08-01', updatedAt: '2026-01-20' }),
  c('code-style-rules', 'Code Style Rules', 'Code style constraints — naming, formatting, imports, file organization', 'rule', ['rules', 'code-style', 'naming', 'formatting', 'imports'], ['claude-code', 'cursor'], 'npx @aidd.md/cli install rule code-style', '# Code Style Rules\n\nNaming conventions, import ordering, file organization, and formatting standards.', { githubUrl: `${GH}/tree/main/rules/code-style.md`, updatedAt: '2026-01-25' }),
  c('git-workflow-rules', 'Git Workflow Rules', 'Git constraints — commit messages, branching, PR conventions, merge strategies', 'rule', ['rules', 'git', 'commits', 'branching', 'pull-requests'], ['claude-code', 'cursor'], 'npx @aidd.md/cli install rule git-workflow', '# Git Workflow Rules\n\nCommit message format, branching strategy, PR conventions, and merge protocols.', { githubUrl: `${GH}/tree/main/rules/git-workflow.md`, createdAt: '2025-07-01', updatedAt: '2026-01-20' }),
  c('documentation-rules', 'Documentation Rules', 'Documentation constraints — structure, formatting, ADR templates, changelog standards', 'rule', ['rules', 'documentation', 'adr', 'changelog', 'formatting'], ['claude-code', 'cursor'], 'npx @aidd.md/cli install rule documentation', '# Documentation Rules\n\nDocumentation structure, formatting standards, and ADR templates.', { githubUrl: `${GH}/tree/main/rules/documentation.md`, createdAt: '2025-08-01', updatedAt: '2026-01-15' }),
  c('decision-tree-rules', 'Decision Tree Rules', 'Decision-making constraints — when to ask, when to act, escalation protocols', 'rule', ['rules', 'decision-making', 'escalation', 'autonomy'], ['claude-code', 'cursor'], 'npx @aidd.md/cli install rule decision-tree', '# Decision Tree Rules\n\nWhen to ask for guidance, when to act autonomously, and escalation protocols.', { githubUrl: `${GH}/tree/main/rules/decision-tree.md`, createdAt: '2025-09-01', updatedAt: '2026-01-18' }),
  // Templates (12)
  c('routing-template', 'Routing Template', 'Task-to-template mapping with PAUS skill equivalents and fallback chains', 'template', ['routing', 'task-classification', 'templates', 'paus'], ['claude-code'], 'npx @aidd.md/cli install template routing', '# Routing Template\n\nMaps task types to appropriate templates and PAUS skill equivalents.', { githubUrl: `${GH}/tree/main/templates/routing.md`, updatedAt: '2026-01-20' }),
  c('brainstorming-template', 'Brainstorming Template', 'Structured ideation — divergent thinking, convergence, evaluation, selection', 'template', ['brainstorming', 'ideation', 'planning'], ['claude-code'], 'npx @aidd.md/cli install template brainstorming', '# Brainstorming Template\n\nStructured ideation with divergent thinking, convergence, and solution evaluation.', { githubUrl: `${GH}/tree/main/templates/brainstorming.md`, createdAt: '2025-06-15', updatedAt: '2026-01-18' }),
  c('analysis-template', 'Analysis Template', 'Systematic analysis — root cause, impact assessment, recommendation matrix', 'template', ['analysis', 'root-cause', 'impact-assessment'], ['claude-code'], 'npx @aidd.md/cli install template analysis', '# Analysis Template\n\nSystematic analysis with root cause identification and recommendation matrices.', { githubUrl: `${GH}/tree/main/templates/analysis.md`, createdAt: '2025-06-15', updatedAt: '2026-01-15' }),
  c('frontend-template', 'Frontend Template', 'Frontend implementation — component architecture, state management, styling', 'template', ['frontend', 'components', 'state-management', 'styling'], ['claude-code'], 'npx @aidd.md/cli install template frontend', '# Frontend Template\n\nComponent architecture, state management patterns, and styling conventions.', { githubUrl: `${GH}/tree/main/templates/frontend.md`, createdAt: '2025-07-01', updatedAt: '2026-01-20' }),
  c('backend-template', 'Backend Template', 'Backend implementation — API design, service layer, data access, error handling', 'template', ['backend', 'api', 'services', 'data-access'], ['claude-code'], 'npx @aidd.md/cli install template backend', '# Backend Template\n\nAPI design, service architecture, data access patterns, and error handling.', { githubUrl: `${GH}/tree/main/templates/backend.md`, createdAt: '2025-07-01', updatedAt: '2026-01-18' }),
  c('database-template', 'Database Template', 'Database design — schema modeling, migrations, indexing strategies', 'template', ['database', 'schema', 'migrations', 'indexing'], ['claude-code'], 'npx @aidd.md/cli install template database', '# Database Template\n\nSchema modeling, migration strategies, and indexing best practices.', { githubUrl: `${GH}/tree/main/templates/database.md`, createdAt: '2025-07-15', updatedAt: '2026-01-15' }),
  c('testing-template', 'Testing Template', 'Test implementation — test strategies, fixtures, mocking, assertions', 'template', ['testing', 'fixtures', 'mocking', 'assertions'], ['claude-code'], 'npx @aidd.md/cli install template testing', '# Testing Template\n\nTest strategies, fixture patterns, mocking approaches, and assertion best practices.', { githubUrl: `${GH}/tree/main/templates/testing.md`, createdAt: '2025-07-15', updatedAt: '2026-01-18' }),
  c('security-audit-template', 'Security Audit Template', 'Security audit — OWASP checklist, vulnerability classification, remediation plan', 'template', ['security', 'audit', 'owasp', 'vulnerabilities'], ['claude-code'], 'npx @aidd.md/cli install template security-audit', '# Security Audit Template\n\nOWASP-based security audit with vulnerability classification and remediation.', { githubUrl: `${GH}/tree/main/templates/security-audit.md`, createdAt: '2025-08-01', updatedAt: '2026-01-12' }),
  c('api-design-template', 'API Design Template', 'API design — REST/GraphQL conventions, versioning, pagination, error formats', 'template', ['api', 'rest', 'graphql', 'versioning', 'pagination'], ['claude-code'], 'npx @aidd.md/cli install template api-design', '# API Design Template\n\nREST/GraphQL conventions, versioning strategies, and error format standards.', { githubUrl: `${GH}/tree/main/templates/api-design.md`, createdAt: '2025-08-01', updatedAt: '2026-01-20' }),
  c('code-review-template', 'Code Review Template', 'Code review — checklist, severity levels, feedback conventions', 'template', ['code-review', 'checklist', 'feedback', 'quality'], ['claude-code'], 'npx @aidd.md/cli install template code-review', '# Code Review Template\n\nStructured code review with severity levels and actionable feedback.', { githubUrl: `${GH}/tree/main/templates/code-review.md`, createdAt: '2025-08-15', updatedAt: '2026-01-18' }),
  c('performance-template', 'Performance Template', 'Performance optimization — profiling, bottleneck analysis, optimization strategies', 'template', ['performance', 'profiling', 'optimization', 'bottlenecks'], ['claude-code'], 'npx @aidd.md/cli install template performance', '# Performance Template\n\nProfiling workflows, bottleneck analysis, and optimization strategies.', { githubUrl: `${GH}/tree/main/templates/performance.md`, createdAt: '2025-09-01', updatedAt: '2026-01-15' }),
  c('migration-template', 'Migration Template', 'Migration planning — dependency updates, breaking changes, rollback strategies', 'template', ['migration', 'upgrades', 'breaking-changes', 'rollback'], ['claude-code'], 'npx @aidd.md/cli install template migration', '# Migration Template\n\nMigration planning with dependency analysis, breaking change tracking, and rollback strategies.', { githubUrl: `${GH}/tree/main/templates/migration.md`, createdAt: '2025-09-01', updatedAt: '2026-01-12' }),
  // Knowledge (20)
  c('react-tkb', 'React Knowledge', 'React 19 — Server Components, hooks, concurrent features, performance patterns', 'knowledge', ['react', 'hooks', 'server-components', 'concurrent'], ['claude-code', 'cursor'], 'npx @aidd.md/cli install knowledge react', '# React 19 Knowledge\n\nPatterns, hooks, server components, and performance optimization for React 19.', { githubUrl: `${GH}/tree/main/knowledge/frontend/patterns/react-server-components.md`, updatedAt: '2026-01-25' }),
  c('tailwind-tkb', 'Tailwind CSS Knowledge', 'Tailwind CSS 4 — CSS-only config, OKLCH colors, modern variants, @theme', 'knowledge', ['tailwind', 'css', 'styling', 'oklch'], ['claude-code', 'cursor'], 'npx @aidd.md/cli install knowledge tailwind', '# Tailwind CSS 4 Knowledge\n\nCSS-only configuration, OKLCH colors, modern variants, and TW4 patterns.', { githubUrl: `${GH}/tree/main/knowledge/frontend/css/tailwind.md`, updatedAt: '2026-01-20' }),
  c('nextjs-tkb', 'Next.js Knowledge', 'Next.js 15 — App Router, Server Actions, streaming, caching, middleware', 'knowledge', ['nextjs', 'app-router', 'server-actions', 'streaming'], ['claude-code', 'cursor'], 'npx @aidd.md/cli install knowledge nextjs', '# Next.js 15 Knowledge\n\nApp Router patterns, Server Actions, streaming SSR, and caching strategies.', { githubUrl: `${GH}/tree/main/knowledge/frontend/meta-frameworks/nextjs.md`, updatedAt: '2026-01-28' }),
  c('astro-tkb', 'Astro Knowledge', 'Astro 5 — Content Layer, Actions, Islands, ClientRouter, View Transitions', 'knowledge', ['astro', 'islands', 'content-layer', 'static-sites'], ['claude-code', 'cursor'], 'npx @aidd.md/cli install knowledge astro', '# Astro 5 Knowledge\n\nContent Layer API, Actions, Islands architecture, and View Transitions.', { githubUrl: `${GH}/tree/main/knowledge/frontend/meta-frameworks/astro.md`, createdAt: '2025-07-01', updatedAt: '2026-01-22' }),
  c('nestjs-tkb', 'NestJS Knowledge', 'NestJS 11 — Modules, Controllers, Services, Guards, Pipes, Interceptors', 'knowledge', ['nestjs', 'modules', 'controllers', 'services', 'backend'], ['claude-code', 'cursor'], 'npx @aidd.md/cli install knowledge nestjs', '# NestJS 11 Knowledge\n\nModule architecture, dependency injection, guards, pipes, and interceptors.', { githubUrl: `${GH}/tree/main/knowledge/backend/frameworks/nestjs.md`, createdAt: '2025-07-01', updatedAt: '2026-01-25' }),
  c('prisma-tkb', 'Prisma Knowledge', 'Prisma 7 — Schema modeling, type-safe queries, migrations, relations', 'knowledge', ['prisma', 'orm', 'database', 'schema', 'migrations'], ['claude-code', 'cursor'], 'npx @aidd.md/cli install knowledge prisma', '# Prisma 7 Knowledge\n\nSchema modeling, type-safe queries, migration workflows, and relation patterns.', { githubUrl: `${GH}/tree/main/knowledge/data/orms/prisma.md`, createdAt: '2025-07-15', updatedAt: '2026-01-22' }),
  c('drizzle-tkb', 'Drizzle Knowledge', 'Drizzle ORM — SQL-first, type-safe queries, schema, migrations, joins', 'knowledge', ['drizzle', 'orm', 'sql', 'database', 'type-safe'], ['claude-code', 'cursor'], 'npx @aidd.md/cli install knowledge drizzle', '# Drizzle ORM Knowledge\n\nSQL-first ORM with type-safe queries, schema definitions, and migration tooling.', { githubUrl: `${GH}/tree/main/knowledge/data/orms/drizzle.md`, createdAt: '2025-08-01', updatedAt: '2026-01-25' }),
  c('vitest-tkb', 'Vitest Knowledge', 'Vitest 4 — Vite-native testing, snapshots, coverage, mocking, workspaces', 'knowledge', ['vitest', 'testing', 'unit-tests', 'coverage', 'mocking'], ['claude-code', 'cursor'], 'npx @aidd.md/cli install knowledge vitest', '# Vitest 4 Knowledge\n\nVite-native test runner with snapshots, coverage, mocking, and workspace support.', { githubUrl: `${GH}/tree/main/knowledge/testing/unit/vitest.md`, createdAt: '2025-08-01', updatedAt: '2026-01-20' }),
  c('playwright-tkb', 'Playwright Knowledge', 'Playwright — E2E testing, cross-browser, auto-wait, visual regression', 'knowledge', ['playwright', 'e2e', 'testing', 'cross-browser', 'visual-regression'], ['claude-code', 'cursor'], 'npx @aidd.md/cli install knowledge playwright', '# Playwright Knowledge\n\nEnd-to-end testing with auto-wait, cross-browser support, and visual regression.', { githubUrl: `${GH}/tree/main/knowledge/testing/e2e/playwright.md`, createdAt: '2025-08-01', updatedAt: '2026-01-18' }),
  c('zustand-tkb', 'Zustand Knowledge', 'Zustand 5 — Minimal state management, selectors, middleware, devtools', 'knowledge', ['zustand', 'state-management', 'react', 'selectors'], ['claude-code', 'cursor'], 'npx @aidd.md/cli install knowledge zustand', '# Zustand 5 Knowledge\n\nMinimal state management with selectors, middleware, and devtools integration.', { githubUrl: `${GH}/tree/main/knowledge/frontend/patterns/zustand.md`, createdAt: '2025-07-01', updatedAt: '2026-01-22' }),
  c('tauri-tkb', 'Tauri Knowledge', 'Tauri 2 — Rust backend, IPC, permissions, plugins, cross-platform desktop/mobile', 'knowledge', ['tauri', 'desktop', 'rust', 'ipc', 'cross-platform'], ['claude-code', 'cursor'], 'npx @aidd.md/cli install knowledge tauri', '# Tauri 2 Knowledge\n\nRust backend, IPC commands, permission system, and cross-platform development.', { githubUrl: `${GH}/tree/main/knowledge/infrastructure/desktop/tauri.md`, createdAt: '2025-08-01', updatedAt: '2026-01-20' }),
  c('docker-tkb', 'Docker Knowledge', 'Docker — Dockerfile best practices, multi-stage builds, compose, networking', 'knowledge', ['docker', 'containers', 'multi-stage', 'compose', 'networking'], ['claude-code', 'cursor'], 'npx @aidd.md/cli install knowledge docker', '# Docker Knowledge\n\nDockerfile best practices, multi-stage builds, compose patterns, and networking.', { githubUrl: `${GH}/tree/main/knowledge/infrastructure/containers/docker.md`, createdAt: '2025-07-15', updatedAt: '2026-01-18' }),
  c('turborepo-tkb', 'Turborepo Knowledge', 'Turborepo 2 — Task pipelines, caching, filtering, remote cache, boundaries', 'knowledge', ['turborepo', 'monorepo', 'caching', 'pipelines', 'pnpm'], ['claude-code', 'cursor'], 'npx @aidd.md/cli install knowledge turborepo', '# Turborepo 2 Knowledge\n\nTask pipelines, intelligent caching, workspace filtering, and remote cache setup.', { githubUrl: `${GH}/tree/main/knowledge/tooling/monorepos/turborepo.md`, createdAt: '2025-08-01', updatedAt: '2026-01-20' }),
  c('zod-tkb', 'Zod Knowledge', 'Zod 4 — Schema validation, type inference, transforms, refinements', 'knowledge', ['zod', 'validation', 'schema', 'type-inference', 'typescript'], ['claude-code', 'cursor'], 'npx @aidd.md/cli install knowledge zod', '# Zod 4 Knowledge\n\nSchema validation, type inference, transforms, refinements, and API boundary patterns.', { githubUrl: `${GH}/tree/main/knowledge/tooling/validation/zod.md`, createdAt: '2025-07-01', updatedAt: '2026-01-25' }),
  c('hono-tkb', 'Hono Knowledge', 'Hono — Ultrafast web framework for edge, Cloudflare Workers, Deno, Node.js', 'knowledge', ['hono', 'edge', 'cloudflare-workers', 'web-framework'], ['claude-code', 'cursor'], 'npx @aidd.md/cli install knowledge hono', '# Hono Knowledge\n\nUltrafast web framework for edge computing with Cloudflare Workers, Deno, and Node.js.', { githubUrl: `${GH}/tree/main/knowledge/backend/frameworks/hono.md`, createdAt: '2025-09-01', updatedAt: '2026-01-28' }),
  c('expo-tkb', 'Expo Knowledge', 'Expo 54 — Expo Router, EAS Build, Config Plugins, native modules', 'knowledge', ['expo', 'react-native', 'mobile', 'eas', 'router'], ['claude-code', 'cursor'], 'npx @aidd.md/cli install knowledge expo', '# Expo 54 Knowledge\n\nExpo Router, EAS Build workflows, Config Plugins, and native module integration.', { githubUrl: `${GH}/tree/main/knowledge/frontend/meta-frameworks/expo.md`, createdAt: '2025-08-01', updatedAt: '2026-01-22' }),
  c('postgresql-tkb', 'PostgreSQL Knowledge', 'PostgreSQL — Indexing, JSON/JSONB, CTEs, partitioning, RLS, full-text search', 'knowledge', ['postgresql', 'sql', 'indexing', 'jsonb', 'rls'], ['claude-code', 'cursor'], 'npx @aidd.md/cli install knowledge postgresql', '# PostgreSQL Knowledge\n\nAdvanced indexing, JSON/JSONB, CTEs, table partitioning, and Row-Level Security.', { githubUrl: `${GH}/tree/main/knowledge/data/databases/postgresql.md`, createdAt: '2025-07-15', updatedAt: '2026-01-20' }),
  c('vite-tkb', 'Vite Knowledge', 'Vite 7 — Config, plugins, HMR, build optimization, library mode', 'knowledge', ['vite', 'build', 'hmr', 'plugins', 'bundling'], ['claude-code', 'cursor'], 'npx @aidd.md/cli install knowledge vite', '# Vite 7 Knowledge\n\nConfiguration, plugin system, HMR, build optimization, and library mode.', { githubUrl: `${GH}/tree/main/knowledge/tooling/build/vite.md`, createdAt: '2025-08-01', updatedAt: '2026-01-18' }),
  c('heroui-tkb', 'HeroUI Knowledge', 'HeroUI v3 — React Aria compound components, Tailwind v4, theme customization', 'knowledge', ['heroui', 'ui-library', 'react-aria', 'tailwind', 'components'], ['claude-code', 'cursor'], 'npx @aidd.md/cli install knowledge heroui', '# HeroUI v3 Knowledge\n\nReact Aria compound components, Tailwind v4 integration, and theme customization.', { githubUrl: `${GH}/tree/main/knowledge/frontend/ui-libraries/heroui.md`, createdAt: '2025-09-01', updatedAt: '2026-01-28' }),
  c('ddd-tkb', 'Domain-Driven Design Knowledge', 'DDD — Aggregates, entities, value objects, bounded contexts, domain events', 'knowledge', ['ddd', 'aggregates', 'entities', 'bounded-contexts', 'domain-events'], ['claude-code', 'cursor'], 'npx @aidd.md/cli install knowledge ddd', '# Domain-Driven Design Knowledge\n\nAggregates, entities, value objects, bounded contexts, and domain event patterns.', { githubUrl: `${GH}/tree/main/knowledge/patterns/domain-driven-design.md`, createdAt: '2025-08-15', updatedAt: '2026-01-20' }),
  // Spec (6)
  c('asdd-lifecycle-spec', 'ASDD Lifecycle', 'AI-Spec-Driven Development — 8-phase lifecycle from SYNC to IMPLEMENTATION-COMMIT', 'spec', ['asdd', 'lifecycle', 'spec-driven', 'phases', 'methodology'], ['claude-code', 'cursor'], 'npx @aidd.md/cli install spec asdd-lifecycle', '# ASDD Lifecycle\n\nAI-Spec-Driven Development: 8-phase lifecycle where every feature flows through specification before implementation.', { githubUrl: `${GH}/tree/main/spec/asdd-lifecycle.md` }),
  c('bluf-6-spec', 'BLUF-6 Protocol', 'Structured communication — six-part framework prioritizing conclusions and trade-offs', 'spec', ['bluf', 'communication', 'protocol', 'structured-output'], ['claude-code', 'cursor'], 'npx @aidd.md/cli install spec bluf-6', '# BLUF-6 Protocol\n\nSix-part communication framework: Bottom Line > Analysis > Trade-offs > Optimal Path > Black Swans > Unknowns.', { githubUrl: `${GH}/tree/main/spec/bluf-6.md`, updatedAt: '2026-01-28' }),
  c('heuristics-spec', 'Decision Heuristics', '10 operating principles — cognitive tools for consistent decision-making under uncertainty', 'spec', ['heuristics', 'decision-making', 'principles', 'cognitive-tools'], ['claude-code', 'cursor'], 'npx @aidd.md/cli install spec heuristics', '# Decision Heuristics\n\n10 operating principles for consistent, high-quality decision-making under uncertainty.', { githubUrl: `${GH}/tree/main/spec/heuristics.md`, updatedAt: '2026-01-25' }),
  c('memory-layer-spec', 'Memory Layer', 'Persistent structured memory — decisions, mistakes, conventions across sessions', 'spec', ['memory', 'persistence', 'sessions', 'decisions', 'conventions'], ['claude-code', 'cursor'], 'npx @aidd.md/cli install spec memory-layer', '# Memory Layer\n\nPersistent, structured memory that accumulates project decisions, mistakes, and conventions across sessions.', { githubUrl: `${GH}/tree/main/spec/memory-layer.md` }),
  c('version-protocol-spec', 'Version Verification Protocol', '4-step stack validation — detect, verify, and validate project dependencies', 'spec', ['version', 'verification', 'dependencies', 'stack-validation'], ['claude-code', 'cursor'], 'npx @aidd.md/cli install spec version-protocol', '# Version Verification Protocol\n\n4-step process: Detect Project Stack > Load Context > Verify Docs > Anti-Legacy Filter.', { githubUrl: `${GH}/tree/main/spec/version-protocol.md`, createdAt: '2025-07-01', updatedAt: '2026-01-20' }),
  c('supported-agents-spec', 'Supported Agents Registry', 'AI coding agents & editors — configuration paths, skill loading, detection methods', 'spec', ['agents', 'editors', 'configuration', 'detection', 'compatibility'], ['claude-code', 'cursor'], 'npx @aidd.md/cli install spec supported-agents', '# Supported Agents Registry\n\nRegistry of AI coding agents/editors with configuration paths, skill loading, and detection methods.', { githubUrl: `${GH}/tree/main/spec/supported-agents.md`, createdAt: '2025-08-01' }),
];

// ── Generate ─────────────────────────────────────────────────────
let mc = 0, cc = 0;
for (const e of mcpServers) { writeMcpServer(e); mc++; }
for (const e of contentEntries) { writeContentEntry(e); cc++; }
console.log(`Seeded ${mc} MCP servers + ${cc} content entries = ${mc + cc} total`);
